### ISSUE TITLE
Invalid FillValue in the individual sensor's AVGTAU

### ISSUE THREAD

**Issue by zhaohuizhangnasa** [zhaohuizhangnasa/aerosol-data-fusion#4]
@rlevy1109 @jwei-openscapes @pawanpgupta @VP Kiliyanpilakkil
zeros are used instead of the fill value in the individual sensor's datasets. Attached is the example case using only one ABI16 input file.
[fillvalue_issue.pptx](https://github.com/zhaohuizhangnasa/aerosol-data-fusion/files/14126647/fillvalue_issue.pptx)

I have created the branch fix/fillvalue_zzu to fix all the fillvalue realted issues.

**Comment by rlevy1109** [comment]
Yes, this needs to be fixed.

*********************************************
Dr. Robert C. Levy  (he/him)
GOES-R Project Scientist
Dark Target Web: https://darktarget.gsfc.nasa.gov/
Bio: https://science.gsfc.nasa.gov/sed/bio/robert.c.levy
NASA Goddard Space Flight Center
O: (301)614-6123  C: (301)237-9086
*********************************************

From: Zhaohui ***@***.***>
Reply-To: zhaohuizhangnasa/aerosol-data-fusion ***@***.***>
Date: Thursday, February 1, 2024 at 9:28 AM
To: zhaohuizhangnasa/aerosol-data-fusion ***@***.***>
Cc: "Levy, Robert C. (GSFC-6130)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] [zhaohuizhangnasa/aerosol-data-fusion] Invalid FillValue in the individual sensor's AVGTAU (Issue #4)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



@rlevy1109<https://github.com/rlevy1109> @jwei-openscapes<https://github.com/jwei-openscapes> @pawanpgupta<https://github.com/pawanpgupta> @vp<https://github.com/vp> Kiliyanpilakkil
zeros are used instead of the fill value in the individual sensor's datasets. Attached is the example case using only one ABI16 input file.
fillvalue_issue.pptx<https://github.com/zhaohuizhangnasa/aerosol-data-fusion/files/14126647/fillvalue_issue.pptx>

I have created the branch fix/fillvalue_zzu to fix all the fillvalue realted issues.

**Comment by zhaohuizhangnasa** [comment]
@rlevy1109 @jwei-openscapes @pawanpgupta @vp Kiliyanpilakkil
Rob, Pawan, Praju, I already fixed the fillvalue and scale factor related issues in the fix/fillvale-zzh branch. Can you check out this branch, run a case and  let me know if everything looks good for you? If there is no further issue, I am going to merge the codes to the main and make the release.
Although I tried to fix the issues in a more generic way, the current codes are still a little bit DT L2 oriented. I will update the codes later for the applications to other data products.

**Comment by rlevy1109** [comment]
Yay!

So what is next step?
Regards,
-Rob



*********************************************
Dr. Robert C. Levy  (he/him)
GOES-R Project Scientist
Dark Target Web: https://darktarget.gsfc.nasa.gov/
Bio: https://science.gsfc.nasa.gov/sed/bio/robert.c.levy
NASA Goddard Space Flight Center
O: (301)614-6123  C: (301)237-9086
*********************************************

From: Zhaohui ***@***.***>
Reply-To: zhaohuizhangnasa/aerosol-data-fusion ***@***.***>
Date: Tuesday, February 13, 2024 at 10:07 AM
To: zhaohuizhangnasa/aerosol-data-fusion ***@***.***>
Cc: "Levy, Robert C. (GSFC-6130)" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] [BULK] Re: [zhaohuizhangnasa/aerosol-data-fusion] Invalid FillValue in the individual sensor's AVGTAU (Issue #4)

CAUTION: This email originated from outside of NASA.  Please take care when clicking links or opening attachments.  Use the "Report Message" button to report suspicious messages to the NASA SOC.



Closed #4<https://github.com/zhaohuizhangnasa/aerosol-data-fusion/issues/4> as completed.
